### PR TITLE
Add support for visionOS

### PR DESCRIPTION
**Pull request by JrGoodle**

### CODE REVIEW

**Comment by heckj** [comment]
Thanks @JrGoodle - but I want to make sure older versions of Swift can still work with this, so uniformly jumping up to Swift 5.9 isn't something I want to do. We can make a parallel Package.swift setup for the 5.9 space that I think will cover this.

**Comment by JrGoodle** [comment]
ok sounds good, I can stick with my fork for now to mess around

**Comment by heckj** [comment]
No worries - I'll get this in, I just need to add a few files to maintain backwards compatibility. There's a trick or two with alternative Package.swift files for different swift versions

**Comment by heckj** [comment]
Thanks for the push to get that updated!

**Comment by JrGoodle** [comment]
TIL how to handle different swift versions with SPM 😄

**Comment by heckj** [comment]
Well, I (in turn) learned it from the folks that managed https://github.com/apple/swift-log - including some of the odder pitfalls that meant I had to have a version for 5.6, 5.7 and 5.8. Hopefully 5.9 will hold for a while ;-)

**Comment by heckj** [comment]
Kind of a random follow-up question @JrGoodle - what caused the need to add in the explicit platform declaration? I just tried adding another swift package that didn't explicitly say "visionOS" in the platforms to a VisionOS only app and had no immediate issue with it. Is there something in the archive/release process that requires this additional bit in place?

**Comment by JrGoodle** [comment]
I think you're right that it may not have been necessary. the platform check might have been the only thing causing issues. I was trying to get https://github.com/chdominguez/Atomic compiling for the native visionOS simulator rather than the iPad compatibility one and there were a few packages needing updates to fix compilation, and I think the first thing I tried was adding the platform and then fixed the check. but I did notice that it compiled fine without some of the packages listing the platform explicitly. this is the first I've started messing around with anything on visionOS so I'm still not exactly sure how library target configuration is supposed to work

**Comment by JrGoodle** [comment]
ok yeah, after reading a bit more I think explicitly defining the platform would only be necessary if the minimum visionOS deployment target was greater than 1. but since it's only on the first version it's not necessary. sorry for the unnecessary churn

**Pull request merged**
